security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
            logout:
                path: app_logout
                target: frontend_home
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles: ROLE_AUTHOR }
        - { path: ^/api, roles: ROLE_USER }

    role_hierarchy:
        ROLE_SUBSCRIBER: []
        ROLE_CONTRIBUTOR: [ROLE_SUBSCRIBER]
        ROLE_AUTHOR: [ROLE_CONTRIBUTOR]
        ROLE_EDITOR: [ROLE_AUTHOR]
        ROLE_ADMIN: [ROLE_EDITOR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]