<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Language extends \App\Entity\Language implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'categoryTranslations' => [parent::class, 'categoryTranslations', null, 16],
        "\0".parent::class."\0".'code' => [parent::class, 'code', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isActive' => [parent::class, 'isActive', null, 16],
        "\0".parent::class."\0".'isDefault' => [parent::class, 'isDefault', null, 16],
        "\0".parent::class."\0".'menuTranslations' => [parent::class, 'menuTranslations', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'pageTranslations' => [parent::class, 'pageTranslations', null, 16],
        "\0".parent::class."\0".'postTranslations' => [parent::class, 'postTranslations', null, 16],
        "\0".parent::class."\0".'tagTranslations' => [parent::class, 'tagTranslations', null, 16],
        'categoryTranslations' => [parent::class, 'categoryTranslations', null, 16],
        'code' => [parent::class, 'code', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isActive' => [parent::class, 'isActive', null, 16],
        'isDefault' => [parent::class, 'isDefault', null, 16],
        'menuTranslations' => [parent::class, 'menuTranslations', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'pageTranslations' => [parent::class, 'pageTranslations', null, 16],
        'postTranslations' => [parent::class, 'postTranslations', null, 16],
        'tagTranslations' => [parent::class, 'tagTranslations', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
