<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Category extends \App\Entity\Category implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'children' => [parent::class, 'children', null, 16],
        "\0".parent::class."\0".'color' => [parent::class, 'color', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'icon' => [parent::class, 'icon', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'menuOrder' => [parent::class, 'menuOrder', null, 16],
        "\0".parent::class."\0".'parent' => [parent::class, 'parent', null, 16],
        "\0".parent::class."\0".'posts' => [parent::class, 'posts', null, 16],
        "\0".parent::class."\0".'slug' => [parent::class, 'slug', null, 16],
        "\0".parent::class."\0".'translations' => [parent::class, 'translations', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'children' => [parent::class, 'children', null, 16],
        'color' => [parent::class, 'color', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'icon' => [parent::class, 'icon', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'menuOrder' => [parent::class, 'menuOrder', null, 16],
        'parent' => [parent::class, 'parent', null, 16],
        'posts' => [parent::class, 'posts', null, 16],
        'slug' => [parent::class, 'slug', null, 16],
        'translations' => [parent::class, 'translations', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
