<?php

namespace ContainerO1TNx7A;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZAUGEyPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZAUGEyP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZAUGEyP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'category' => ['privates', '.errored..service_locator.ZAUGEyP.App\\Entity\\Category', NULL, 'Cannot autowire service ".service_locator.ZAUGEyP": it needs an instance of "App\\Entity\\Category" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'category' => 'App\\Entity\\Category',
        ]);
    }
}
