<?php

namespace ContainerO1TNx7A;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getComment2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.JRyFIf6.App\Entity\Comment' shared service.
     *
     * @return \App\Entity\Comment
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.JRyFIf6": it needs an instance of "App\\Entity\\Comment" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
