<?php

namespace ContainerO1TNx7A;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZAUGEyP.App\Controller\Admin\CategoryController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZAUGEyP.App\\Controller\\Admin\\CategoryController::show()'] = ($container->privates['.service_locator.ZAUGEyP'] ?? $container->load('get_ServiceLocator_ZAUGEyPService'))->withContext('App\\Controller\\Admin\\CategoryController::show()', $container);
    }
}
