<?php

namespace ContainerO1TNx7A;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLanguageControllertoggleActiveService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XqcJSAx.App\Controller\Admin\LanguageController::toggleActive()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XqcJSAx.App\\Controller\\Admin\\LanguageController::toggleActive()'] = ($container->privates['.service_locator.XqcJSAx'] ?? $container->load('get_ServiceLocator_XqcJSAxService'))->withContext('App\\Controller\\Admin\\LanguageController::toggleActive()', $container);
    }
}
