<?php

namespace ContainerO1TNx7A;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMenuControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dDUokf8.App\Controller\Admin\MenuController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dDUokf8.App\\Controller\\Admin\\MenuController::edit()'] = ($container->privates['.service_locator.dDUokf8'] ?? $container->load('get_ServiceLocator_DDUokf8Service'))->withContext('App\\Controller\\Admin\\MenuController::edit()', $container);
    }
}
