<?php

namespace ContainerO1TNx7A;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMediaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.x90VASC.App\Entity\Media' shared service.
     *
     * @return \App\Entity\Media
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.x90VASC": it needs an instance of "App\\Entity\\Media" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
