<?php

namespace ContainerO1TNx7A;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\TagController' shared autowired service.
     *
     * @return \App\Controller\Admin\TagController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/TagController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/SlugService.php';

        $container->services['App\\Controller\\Admin\\TagController'] = $instance = new \App\Controller\Admin\TagController(($container->privates['App\\Repository\\TagRepository'] ?? $container->load('getTagRepositoryService')), ($container->privates['App\\Service\\LanguageService'] ?? $container->load('getLanguageServiceService')), ($container->privates['App\\Service\\SlugService'] ??= new \App\Service\SlugService()), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\Admin\\TagController', $container));

        return $instance;
    }
}
