<?php

namespace Container9OQs4gx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X90VASCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.x90VASC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.x90VASC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'media' => ['privates', '.errored..service_locator.x90VASC.App\\Entity\\Media', NULL, 'Cannot autowire service ".service_locator.x90VASC": it needs an instance of "App\\Entity\\Media" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'media' => 'App\\Entity\\Media',
        ]);
    }
}
