<?php

namespace Container9OQs4gx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_78wiA30Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.78wiA30' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.78wiA30'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tag' => ['privates', '.errored..service_locator.78wiA30.App\\Entity\\Tag', NULL, 'Cannot autowire service ".service_locator.78wiA30": it needs an instance of "App\\Entity\\Tag" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'tag' => 'App\\Entity\\Tag',
        ]);
    }
}
