<?php

namespace Container9OQs4gx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JDLyg2zService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JDLyg2z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JDLyg2z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'page' => ['privates', '.errored..service_locator.JDLyg2z.App\\Entity\\Page', NULL, 'Cannot autowire service ".service_locator.JDLyg2z": it needs an instance of "App\\Entity\\Page" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'page' => 'App\\Entity\\Page',
        ]);
    }
}
