<?php

namespace Container9OQs4gx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EWAQaZuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EWAQaZu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EWAQaZu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.EWAQaZu.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.EWAQaZu": it needs an instance of "App\\Entity\\User" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'user' => 'App\\Entity\\User',
        ]);
    }
}
