<?php

namespace Container9OQs4gx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DDUokf8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dDUokf8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dDUokf8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'menu' => ['privates', '.errored..service_locator.dDUokf8.App\\Entity\\Menu', NULL, 'Cannot autowire service ".service_locator.dDUokf8": it needs an instance of "App\\Entity\\Menu" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'menu' => 'App\\Entity\\Menu',
        ]);
    }
}
