<?php

namespace Container9OQs4gx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentControllerapproveService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JRyFIf6.App\Controller\Admin\CommentController::approve()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JRyFIf6.App\\Controller\\Admin\\CommentController::approve()'] = ($container->privates['.service_locator.JRyFIf6'] ?? $container->load('get_ServiceLocator_JRyFIf6Service'))->withContext('App\\Controller\\Admin\\CommentController::approve()', $container);
    }
}
