<?php

namespace Container9OQs4gx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentControllerreplyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FYeieEv.App\Controller\Admin\CommentController::reply()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FYeieEv.App\\Controller\\Admin\\CommentController::reply()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'parentComment' => ['privates', '.errored..service_locator.FYeieEv.App\\Entity\\Comment', NULL, 'Cannot autowire service ".service_locator.FYeieEv": it needs an instance of "App\\Entity\\Comment" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'parentComment' => 'App\\Entity\\Comment',
        ]))->withContext('App\\Controller\\Admin\\CommentController::reply()', $container);
    }
}
