<?php

namespace Container9OQs4gx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntityTimestampListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\EntityTimestampListener' shared autowired service.
     *
     * @return \App\EventListener\EntityTimestampListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/EntityTimestampListener.php';
        include_once \dirname(__DIR__, 4).'/src/Service/SlugService.php';

        return $container->privates['App\\EventListener\\EntityTimestampListener'] = new \App\EventListener\EntityTimestampListener(($container->privates['App\\Service\\SlugService'] ??= new \App\Service\SlugService()));
    }
}
