<?php

namespace Container9OQs4gx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExtensionControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\ExtensionController' shared autowired service.
     *
     * @return \App\Controller\Admin\ExtensionController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/ExtensionController.php';
        include_once \dirname(__DIR__, 4).'/src/Extension/PluginManager.php';
        include_once \dirname(__DIR__, 4).'/src/Extension/HookManager.php';
        include_once \dirname(__DIR__, 4).'/src/Extension/ThemeManager.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));
        $b = ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'));

        $container->services['App\\Controller\\Admin\\ExtensionController'] = $instance = new \App\Controller\Admin\ExtensionController(new \App\Extension\PluginManager($a, new \App\Extension\HookManager($b), $b, \dirname(__DIR__, 4)), new \App\Extension\ThemeManager($a, $b, ($container->privates['twig'] ?? self::getTwigService($container)), \dirname(__DIR__, 4)));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\Admin\\ExtensionController', $container));

        return $instance;
    }
}
