<?php

namespace Container9OQs4gx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrontendControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\FrontendController' shared autowired service.
     *
     * @return \App\Controller\FrontendController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/FrontendController.php';

        $container->services['App\\Controller\\FrontendController'] = $instance = new \App\Controller\FrontendController(($container->privates['App\\Repository\\PostRepository'] ?? $container->load('getPostRepositoryService')), ($container->privates['App\\Repository\\PageRepository'] ?? $container->load('getPageRepositoryService')), ($container->privates['App\\Repository\\CategoryRepository'] ?? $container->load('getCategoryRepositoryService')), ($container->privates['App\\Repository\\TagRepository'] ?? $container->load('getTagRepositoryService')), ($container->privates['App\\Repository\\MenuRepository'] ?? $container->load('getMenuRepositoryService')), ($container->privates['App\\Service\\LanguageService'] ?? $container->load('getLanguageServiceService')));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\FrontendController', $container));

        return $instance;
    }
}
