<?php

namespace Container9OQs4gx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLanguageServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\LanguageService' shared autowired service.
     *
     * @return \App\Service\LanguageService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/LanguageService.php';

        return $container->privates['App\\Service\\LanguageService'] = new \App\Service\LanguageService(($container->privates['App\\Repository\\LanguageRepository'] ?? $container->load('getLanguageRepositoryService')), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
