<?php

namespace Container9OQs4gx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMediaControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.x90VASC.App\Controller\Admin\MediaController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.x90VASC.App\\Controller\\Admin\\MediaController::edit()'] = ($container->privates['.service_locator.x90VASC'] ?? $container->load('get_ServiceLocator_X90VASCService'))->withContext('App\\Controller\\Admin\\MediaController::edit()', $container);
    }
}
