<?php

namespace Container9OQs4gx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPageControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JDLyg2z.App\Controller\Admin\PageController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JDLyg2z.App\\Controller\\Admin\\PageController::delete()'] = ($container->privates['.service_locator.JDLyg2z'] ?? $container->load('get_ServiceLocator_JDLyg2zService'))->withContext('App\\Controller\\Admin\\PageController::delete()', $container);
    }
}
