<?php

namespace Container9OQs4gx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPageControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\PageController' shared autowired service.
     *
     * @return \App\Controller\Admin\PageController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/PageController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/SlugService.php';

        $container->services['App\\Controller\\Admin\\PageController'] = $instance = new \App\Controller\Admin\PageController(($container->privates['App\\Repository\\PageRepository'] ?? $container->load('getPageRepositoryService')), ($container->privates['App\\Repository\\MediaRepository'] ?? $container->load('getMediaRepositoryService')), ($container->privates['App\\Service\\LanguageService'] ?? $container->load('getLanguageServiceService')), ($container->privates['App\\Service\\SlugService'] ??= new \App\Service\SlugService()), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\Admin\\PageController', $container));

        return $instance;
    }
}
