<?php

namespace Container9OQs4gx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.JDLyg2z.App\Entity\Page' shared service.
     *
     * @return \App\Entity\Page
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.JDLyg2z": it needs an instance of "App\\Entity\\Page" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
