<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.a4476964.js',
                '/build/506.5625cb45.js',
                '/build/app.583b1f3e.js',
            ],
            'css' => [
                '/build/app.6afac2a6.css',
            ],
        ],
    ],
],

]];
